#Dropwizard
database:
  name: ${env.DB_NAME}
  host: ${env.DB_HOST}
  port: ${env.DB_PORT}
  user: ${env.DB_USER}
  password: ${env.DB_PASSWORD}

benchflow.env:
  config.yml: /app/config.yml

drivers-maker:
  address: ${env.DRIVERS_MAKER_ADDRESS}

faban:
  user: ${env.FABAN_USER!""}
  password: ${env.FABAN_PASSWORD!""}
  address: ${env.FABAN_ADDRESS}
  submitRetries: ${env.FABAN_SUBMIT_RETRIES!5}

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      #bindHost: 127.0.0.1 # only bind to loopback
  adminConnectors:
    - type: http
      port: 8081
      #bindHost: 127.0.0.1 # only bind to loopback

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    cloud.benchflow.experimentsmanager.resources.lifecycle.v2.RunBenchmarkResource: ALL
    cloud.benchflow.experimentsmanager.resources.lifecycle.v2.DeployBenchmarkResource: ALL
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout