#Dropwizard

minio:
  accessKey: ${env.MINIO_ACCESS_KEY}
  secretKey: ${env.MINIO_SECRET_KEY}
  address: ${env.MINIO_ADDRESS}
 
faban:
  user: ${env.FABAN_USER!""}
  password: ${env.FABAN_PASSWORD!""}
  address: ${env.FABAN_ADDRESS}

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      #bindHost: 127.0.0.1 # only bind to loopback
  adminConnectors:
    - type: http
      port: 8081
      #bindHost: 127.0.0.1 # only bind to loopback
     
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    DeployBenchmarkResourceLogger: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout