#Dropwizard

minio:
  accessKey: CYNQML6R7V12MTT32W6P
  secretKey: SQ96V5pg02Z3kZ/0ViF9YY6GwWzZvoBmElpzEEjn
  address: http://195.176.181.55:9000/

drivers.maker:
  address: http://localhost:6060

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1 # only bind to loopback
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1 # only bind to loopback
     
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    DeployBenchmarkResourceLogger: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout